### PR TITLE
Fix empty result with jsonpath

### PR DESCRIPTION
**Pull request by rajiv-g**
## Pull Request Checklist

#73 

#### General

- [ ] Update Changelog following the conventions listed [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by mike-stewart** [comment]
@jspaleta @majormoses Any interest in pulling this? This fixes a big blocker for us.

**Comment by majormoses** [comment]
Hey sorry for the lapse. I will take a look in a minute.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
I will look to make sure we cut a release this weekend, I have merged a lot of PRs this evening so our pipeline is clogged right now so I will circle back for it. Feel free to ping me on Monday if there is no release out yet.

**Comment by rajiv-g** [comment]
@majormoses Waiting for new release

**Comment by rajiv-g** [comment]
@majormoses Would you mind to create a new release?

**Pull request merged**
