### PR TITLE
Read key=value tags from check output

### PR DESCRIPTION
**Pull request by mattk42**
I needed the ability to add custom tags in the check result rather than in the check definition. This is the quick solution I am giving a shot in my environment.

### CODE REVIEW

**Comment by sstarcher** [comment]
Can you document the syntax and rebase.

**Comment by envintus** [comment]
@mattk42 Could you follow up with this PR?

**Comment by mattk42** [comment]
Hope to get back to this soon. Took a look a while back and the merge was
pretty nasty. Haven't had a good opportunity to spend time on it.

**Comment by majormoses** [comment]
@mattk42 any plans to revisit?

**Comment by majormoses** [comment]
closing due to inactivity, please reply back if you want to work on getting this over the line.

**Pull request closed without merging**
